# See config.example.yml for documentation.
object_base: orig/WBME_1
object: 00000001.dol
hash: 328b451e369e8d305a65c00ca710eb8175fe9f0a
symbols: config/WBME_1/symbols.txt
splits: config/WBME_1/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11
